name: Deploy Portfolio

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Deploy al servidor
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /opt/portafolio
            git pull origin main
            docker build -t portafolio .
            docker stop portafolio || true
            docker rm portafolio || true
            docker run -d \
              --name portafolio \
              --restart=always \
              -p 3000:80 \
              portafolio